### ISSUE TITLE
Buildroot Environment Setup

### ISSUE THREAD

**Issue by GautamaGandhi** [cu-ecen-aeld/final-project-GautamaGandhi#1]
**DoD:**

- [x]  Build a custom Linux image using buildroot for Raspberry Pi.
- [x]  Flash the image onto the Raspberry Pi.
- [x]  Successful boot-up of Raspberry Pi with custom image.

**Comment by neohere97** [comment]
Got the Buildroot image working, had some issues flashing to the SD card. Need to add some necessary packages and test next.

The following resources were studied/consulted to get this working
1) [Setting up Buildroot for Hardware Builds](https://github.com/cu-ecen-aeld/buildroot-assignments-base/wiki/Setting-up-Buildroot-for-Hardware-Builds)

2) https://www.youtube.com/watch?v=84T-P5ye864

3)https://bootlin.com/doc/training/buildroot/buildroot-slides.pdf


![image](https://user-images.githubusercontent.com/18268460/201545785-9bd3f701-af29-4a34-b35c-153a85203e7e.png)


Issue closed with [commit](https://github.com/cu-ecen-aeld/final-project-neohere97/commit/d3dc7153ecf22a4504ecff434479e158895193ab)
