### ISSUE TITLE
Userspace socket client 

### ISSUE THREAD

**Issue by neohere97** [cu-ecen-aeld/final-project-GautamaGandhi#10]
**DoD**

- [x]  Reception of image data over the socket in desired format
- [x]  Rendering image data onto LED matrix
- [x] Multithreaded implementation to decouple IO from processing

Blockers:
- Socket communication issues
- Unable to render images onto LED matrix
#8

**Comment by GautamaGandhi** [comment]
Client implementation was completed and the following was accomplished:
1. Image data sent by the server was received, processed and converted to the desired format for the RGB LED matrix. Data was received in a byte-by-byte format of Red, Green and Blue and converted to a uint32_t format for the LED matrix.
2. Image data was successfully rendered onto the LED matrix. The [RPI WS281x library](https://github.com/jgarff/rpi_ws281x) was used for this.
3. The Client and Server implementation was first tested using Raspbian OS on the same Raspberry Pi, followed by Raspbian OS on two devices and finally adding them using buildroot and testing.

The video has been added in the[ Server issue](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/issues/9) page.

The corresponding commits are: [Client Implementation](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/commit/b4c59671afb0274463387064e504d43ab0e71d8a), [Buildroot Addition](https://github.com/cu-ecen-aeld/final-project-neohere97/commit/8a7fa8b4f084297c763af89e8400c65452435c65).
