### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by neohere97** [cu-ecen-aeld/final-project-GautamaGandhi#11]
**DoD:**

- [x] Code Cleanup for Socket Server
- [x] Code Cleanup for Socket Client

Blockers:
None

**Comment by GautamaGandhi** [comment]
Code cleanup complete for the socket client. Added multithreaded implementation to accommodate a management socket. Management socket server runs on the OpenWRT image. 
Code: [Commit](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/commit/c9843bdc654f9a0e1d6b0e14dd0f42a28e00d6d6)

**Comment by neohere97** [comment]
The code has been cleaned up for the socket server. Multithreaded implementation is yet to be done.

Code -> [commit](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/commit/2430866eb03ae7a63e43f9ff33db35cf080ef355)
