### ISSUE TITLE
GPIO & PWM Baremetal using mmap

### ISSUE THREAD

**Issue by neohere97** [cu-ecen-aeld/final-project-GautamaGandhi#15]
**Description:**
This issue describes the control of the GPIO and PWM peripherals on a Raspberry Pi 4 Model B SBC by using the mmap() system call. 

**DoD:**

- [x] Enable GPIO and PWM using mmap
- [x] Verify correct functionality on Buildroot image

**Comment by neohere97** [comment]
https://user-images.githubusercontent.com/18268460/205776508-e56a58e2-5afb-4018-ad8b-859b12c2b812.mp4

**Comment by neohere97** [comment]
![WhatsApp Video 2022-12-05 at 17 30 46](https://user-images.githubusercontent.com/18268460/205776664-00a68f30-92db-4a3f-bbdc-721f5ae62ce2.gif)

**Comment by GautamaGandhi** [comment]
The mmap system call has been used to map the physical addresses of the GPIO and PWM peripherals to virtual memory. This allows us to access and control the peripherals by directly accessing the registers in a "bare-metal" fashion. The PWM functionality was verified using a simple LED circuit as shown above. The commit is [here](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/commit/dca3c354b2b5e3c3525f49cc166bd1afda332a82).
