### ISSUE TITLE
Camera Software Setup

### ISSUE THREAD

**Issue by GautamaGandhi** [cu-ecen-aeld/final-project-GautamaGandhi#3]
**DoD:**

- [x] Verify USB camera driver and APIs to use.
- [x] Programmatically capture test images.

Blockers:
- Unable to access the driver.
- Unable to capture test images in desired format.

**Comment by neohere97** [comment]
UVCvideo driver and respective userspace APIs will be used to capture images from the Webcam. This has been tested on Raspberry Pi OS, Images have been captured programmatically on the Raspberry Pi OS at the resolution of 320 x 240, which is the minimum supported by the camera.

![image](https://user-images.githubusercontent.com/18268460/201753334-88b63f21-3d1c-4356-a98f-ae135d094a8c.png)

![image](https://user-images.githubusercontent.com/18268460/201753533-99f80305-4b75-46cf-8e86-cb79152435b5.png)

![image](https://user-images.githubusercontent.com/18268460/201753722-2ec1a217-c258-4e73-a0e0-d3f2d222e5cb.png)


Issue closed with [commit](https://github.com/cu-ecen-aeld/final-project-GautamaGandhi/commit/3254d913721922a8be2724cef0f2af5e8b766835).
