### ISSUE TITLE
SSH into Raspberry Pi

### ISSUE THREAD

**Issue by GautamaGandhi** [cu-ecen-aeld/final-project-GautamaGandhi#4]
**DoD:** 

- [x] Adding Dropbear package to linux image.
- [x] Successfully logging into Raspberry Pi using SSH.

Blockers:
- Buildroot Environment setup incorrectly/ incomplete
#1

**Comment by neohere97** [comment]
1. Used OpenSSH instead of Dropbear
2. Enabled SSH from sshd_config
3. Enabled root user login and password authentication since this is a project setup

![image](https://user-images.githubusercontent.com/18268460/201544730-c5c9fb77-de1a-4086-9739-2d88380b5eaf.png)
