### ISSUE TITLE
Image RGB Capture and Processing

### ISSUE THREAD

**Issue by neohere97** [cu-ecen-aeld/final-project-GautamaGandhi#7]
**DoD:**

- [x] Implement RGB Image Capture
- [x] User code implementation to convert image resolution to match display resolution (16 x 16)
- [x] GRB pixel data packing instead of RGB to match LED Matrix Format

Blockers:
- Unable to setup Camera Software.
#3

**Comment by neohere97** [comment]
![image](https://user-images.githubusercontent.com/18268460/201750045-dc32b37a-02b5-4ac8-9089-0330b0d55493.png)

RGB Image capture has been implemented using the Linux video library and UVC driver. The code has been leveraged from RTES course, adapted by Sam Siewert. 

Next the code needs to be further refactored to have an API which returns RGB pixel data as needed by the Socket Server.

**Comment by GautamaGandhi** [comment]
Pushing this issue to Sprint 3 due to blocker related to packing.

**Comment by neohere97** [comment]
The downsizing of the image has been completed. Initially, code was written from scratch to do the cropping and downsampling/downsizing. But later an open-source header library was found which could do the same with many more features. 

Below is a downsampled image from 320 x 240 to 16x16 matching the target resolution

The open source library has been linked in the project overview
![image](https://user-images.githubusercontent.com/18268460/204058853-fc2f7ef0-6e1b-496f-8ea2-d955ec88b60c.png)

**Comment by neohere97** [comment]
RGB/GRB packing switch has been added, this will happen during the conversion from YUYV to RGB.
