### ISSUE TITLE
Test LED Matrix on Rasp Pi

### ISSUE THREAD

**Issue by neohere97** [cu-ecen-aeld/final-project-GautamaGandhi#8]
**DoD**

- [x] Implement open source driver (user space)
- [x] Render demo pixel data on the matrix with Raspberry Pi driver

Blocker:
- Unable to utilise hardware modules in Buildroot Image (GPIO, PWM, PCM)
#5 

Update: 
- Tested the functionality in Raspbian OS using example code.

**Comment by neohere97** [comment]
https://user-images.githubusercontent.com/18268460/201573733-39f0799e-82b8-4940-8f8c-cefc53125079.mp4

**Comment by GautamaGandhi** [comment]
Able to render pixel data onto the LED_Matrix. Tested on Raspbian OS. 
Deciding to perform pre-processing on server after image capture or client after server sends the 16x16 image data. 
Next task is to tie this up with the Socket Client implementation.
